# Generated by Django 3.0.6 on 2020-06-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
